In [1]:
import numpy as np
#create a list
list1=[1,2,3]
array1=np.array(list1)
print(array1)


[1 2 3]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
list1=[1,2,3]
array1=np.array([2,4,6,8])
print(array1)


[2 4 6 8]


In [5]:
import numpy as np

array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [7]:
import numpy as np
array1=np.arange(5)
print(array1)
array2=np.arange(1,9,2)
print(array2)

[0 1 2 3 4]
[1 3 5 7]


In [8]:
import numpy as np
array1=np.random.rand(5)
print(array1)

[0.20439092 0.88291468 0.75418737 0.15127583 0.46294369]


In [9]:
import numpy as np
array1=np.empty(5)
print(array1)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]


In [11]:
import numpy as np
array1=np.array([[1,2,3,4],
                [1,2,5,6]])
print(array1)

[[1 2 3 4]
 [1 2 5 6]]


In [12]:
import numpy as np
array1=np.array([[[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]],
                 [[13,14,15,16],
                 [17,18,19,20],
                 [21,22,23,24]]])
print( array1 )

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
import numpy as np
array1=np.zeros((2,3))
print(array1)
array2=np.zeros((2,3,4))
print(array2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
import numpy as np
array1=np.random.rand(2,3)
print(array1)
array2=np.random.rand(2,3,4)
print(array2)

[[0.46612736 0.25673892 0.04957002]
 [0.46084994 0.1345162  0.94507085]]
[[[0.42413821 0.82951561 0.23413441 0.78658944]
  [0.97929132 0.55837535 0.37638548 0.34018885]
  [0.77597439 0.73046134 0.0416684  0.63059661]]

 [[0.51596385 0.44367595 0.51076896 0.62088037]
  [0.98007475 0.84602039 0.64514854 0.18678131]
  [0.06211875 0.60388126 0.57567271 0.19987598]]]


In [18]:
import numpy as np
array1=np.full((2,2),5)
print(array1)

[[5 5]
 [5 5]]


In [21]:
import numpy as np
array1=np.array([1,3,7],dtype='int32')
print(array1,array1.dtype)

[1 3 7] int32


In [23]:
import numpy as np
int_array=np.array([1,3,7,5])
print(int_array,int_array.dtype)
float_array=int_array.astype('float')
print(float_array,float_array.dtype)

[1 3 7 5] int64
[1. 3. 7. 5.] float64


In [25]:
import numpy as np
array1=np.array([[1,2,3,4],
                [1,2,5,6]])
print(array1.shape)
print(array1.ndim)
print(array1.dtype)
print(array1.size)


(2, 4)
2
int64
8


In [28]:
import numpy as np
array1=np.array([[1,2,3,4],
                [1,2,5,6]])
np.save('file1.npy',array1)


In [29]:
import numpy as np
array1=np.array([1,3,5,7,9])
print(array1[0])
print(array1[2])
print(array1[4])


1
5
9


In [30]:
import numpy as np
array1=np.array([1,3,5,7,9])
array1[0]=10
array1[2]=14
print("the modified array is")
print(array1)

the modified array is
[10  3 14  7  9]


In [31]:
import numpy as np
array1=np.array([1,3,5,7,9])
print(array1[-1])
print(array1[-2])
print(array1[-4])


9
7
3


In [32]:
import numpy as np
array1=np.array([1,3,5,7,9,2,4,5,6])
print(array1[1:4])
print(array1[2:6])
print(array1[3:])
print(array1[:])
#

[3 5 7]
[5 7 9 2]
[7 9 2 4 5 6]
[1 3 5 7 9 2 4 5 6]


In [33]:

import numpy as np
array1=np.array([1,3,5,7,9,2,4,5,6])
array1[3:]=20
print(array1)

[ 1  3  5 20 20 20 20 20 20]


In [36]:
import numpy as np
array1=np.array([1,3,5,7,9,2,4,5])
result1=np.reshape(array1,(4,2))
print(result1)
result2=np.reshape(array1,(1,8))
print(result2)

[[1 3]
 [5 7]
 [9 2]
 [4 5]]
[[1 3 5 7 9 2 4 5]]


In [37]:
#task1
import numpy as np
array1=np.arange(10)
print(array1)
print(array1[1:6])


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [41]:
import numpy as np

array = np.random.randint(1, 51, size=(3, 3))

sum_of_elements = np.sum(array)

print("array:")
print(array)
print("the sum is")
print( sum_of_elements)

Matrix:
[[ 6 35  3]
 [14  4 19]
 [50 34 20]]

Sum of all elements: 185


In [44]:
import numpy as np
array1=np.linspace(0,20,5)
print(array1)


[ 0.  5. 10. 15. 20.]


In [46]:
import numpy as np

identity_matrix = np.eye(4)
print("the identity matrix is")
print(identity_matrix)

transpose_matrix = identity_matrix.T
print("the transpose is")
print(transpose_matrix)

the identity matrix is
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
the transpose is
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
import numpy as np

array = np.random.randint(1, 51, size=(4, 4))
min_value = np.min(array)
max_value = np.max(array)
print("array:")
print(array)
print("the minimum value is")
print(min_value)
print("the maximum value is")
print(max_value)


array:
[[26 27 42 20]
 [ 7 47 18 27]
 [33 40 20 29]
 [ 6  9 36 35]]
the minimum value is
6
the maximum value is
47


In [48]:
import numpy as np
array1=np.array([1,3,5,7,9,2,4,5,1,2,3,4])
print(array1)
result1=np.reshape(array1,(3,4))
print(result1)


[1 3 5 7 9 2 4 5 1 2 3 4]
[[1 3 5 7]
 [9 2 4 5]
 [1 2 3 4]]


In [51]:
import numpy as np

array = np.random.randint(1, 51, size=(5, 5))
array[array > 20] = 20

# Print the updated array
print(array)

[[20 20 20  8 13]
 [20 13 15 20 20]
 [20 20 13  8 20]
 [20 20 20 20  9]
 [20 20 10 12 20]]


In [52]:
import pandas as pd

array = {'Name': ['hira', 'urwa', 'faryal', 'areeba', 'ayesha'],
        'Age': [25, 30, 22, 28, 26]}

df = pd.DataFrame(array)


print(df)

     Name  Age
0    hira   25
1    urwa   30
2  faryal   22
3  areeba   28
4  ayesha   26


In [64]:
import pandas as pd

df = pd.read_csv('STD_DATA new.csv')


print(df.head())

    name a b c
0    age 1 2 3
1  garde a b c


In [56]:
import pandas as pd

# Sample DataFrame (replace with your actual DataFrame)
d = {'Product': ['A', 'B', 'C'],
        'Price': [1, 2, 3],
        'Quantity': [20, 30, 40]}
df = pd.DataFrame(d)

# Calculate total value
df['Total'] = df['Price'] * df['Quantity']

# Display the updated DataFrame
print(df)

  Product  Price  Quantity  Total
0       A      1        20     20
1       B      2        30     60
2       C      3        40    120


In [58]:
import pandas as pd
df = pd.DataFrame({'Name': ['hira', 'urwa', 'faryal', 'areeba', 'ayesha'],
        'Age': [25, 30, None, 28, 26]})
print(df)
df.fillna(0, inplace=True)
print(df)

     Name   Age
0    hira  25.0
1    urwa  30.0
2  faryal   NaN
3  areeba  28.0
4  ayesha  26.0
     Name   Age
0    hira  25.0
1    urwa  30.0
2  faryal   0.0
3  areeba  28.0
4  ayesha  26.0


In [59]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(5,3), columns=['A', 'B', 'C'])
print(df)
df.sort_values(by=['A'], inplace=True)
print(df)

          A         B         C
0  0.148314  0.342430  0.520366
1  0.420111  0.306313  0.328160
2  0.155857  0.903591  0.361127
3  0.161988  0.369819  0.928119
4  0.558383  0.716103  0.132813
          A         B         C
0  0.148314  0.342430  0.520366
2  0.155857  0.903591  0.361127
3  0.161988  0.369819  0.928119
1  0.420111  0.306313  0.328160
4  0.558383  0.716103  0.132813


In [60]:
import pandas as pd
df = pd.DataFrame({'Name': ['hira', 'urwa', 'faryal', 'areeba', 'ayesha'],
        'Score': [25, 30, 70, 80, 26]})
print(df)
df[df['Score'] > 50]

     Name  Score
0    hira     25
1    urwa     30
2  faryal     70
3  areeba     80
4  ayesha     26


Name  Score
2  faryal     70
3  areeba     80

In [61]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0,100,size=(5, 3)), columns=list('ABC'))
print(df)
df['D'] = df['A'].cumsum()
print(df)

    A   B   C
0  21   3  12
1  40  84  85
2  71  74  83
3  25  24  95
4  81  88  59
    A   B   C    D
0  21   3  12   21
1  40  84  85   61
2  71  74  83  132
3  25  24  95  157
4  81  88  59  238
